import { chromium } from '@playwright/test';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error' && !/ERR_CONNECTION|404/.test(m.text())) errors.push('console: ' + m.text()); });
await page.goto('http://localhost:4321/LexMX/setup', { waitUntil: 'networkidle', timeout: 60000 });
await page.waitForSelector('[data-testid="provider-setup"]', { timeout: 30000 });
await page.waitForTimeout(2000);
await page.click('[data-testid="provider-openai"]');
await page.click('text=Configurar (1)');
await page.waitForSelector('[data-testid="provider-api-key"]', { timeout: 10000 });
await page.fill('[data-testid="provider-api-key"]', 'sk');
await page.click('[data-testid="provider-save"]');
await page.waitForTimeout(800);
const validation = await page.locator('[role="alert"]').allInnerTexts();
await page.fill('[data-testid="provider-api-key"]', 'sk-test-1234567890');
await page.click('[data-testid="provider-save"]');
await page.waitForTimeout(3000);
const stepText = await page.locator('[data-testid="provider-setup"] h2').allInnerTexts();
await page.screenshot({ path: process.argv[2], fullPage: true });
console.log(JSON.stringify({ validation, stepText, errors: errors.slice(0, 6) }, null, 2));
await browser.close();
